# Stage 1: Build the Vite app
FROM node:20-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

# Vite embeds env vars at build time
ARG VITE_API_BASE_URL
ARG VITE_PIXEL_ID
ARG VITE_GA_ID
ARG VITE_TRIAL_CHAT_DURATION
ARG VITE_FREE_WALLET_RECHARGE
ARG VITE_APP_ENV=production
ARG VITE_SOCKET_SERVER_URL
ARG VITE_CHAT_PRICE_PER_MIN
ARG VITE_AUDIO_CALL_PRICE_PER_MIN
ARG VITE_VIDEO_CALL_PRICE_PER_MIN
ARG VITE_FCM_VAPID_KEY
ARG VITE_BASE=/

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_PIXEL_ID=$VITE_PIXEL_ID \
    VITE_GA_ID=$VITE_GA_ID \
    VITE_TRIAL_CHAT_DURATION=$VITE_TRIAL_CHAT_DURATION \
    VITE_FREE_WALLET_RECHARGE=$VITE_FREE_WALLET_RECHARGE \
    VITE_APP_ENV=$VITE_APP_ENV \
    VITE_SOCKET_SERVER_URL=$VITE_SOCKET_SERVER_URL \
    VITE_CHAT_PRICE_PER_MIN=$VITE_CHAT_PRICE_PER_MIN \
    VITE_AUDIO_CALL_PRICE_PER_MIN=$VITE_AUDIO_CALL_PRICE_PER_MIN \
    VITE_VIDEO_CALL_PRICE_PER_MIN=$VITE_VIDEO_CALL_PRICE_PER_MIN \
    VITE_FCM_VAPID_KEY=$VITE_FCM_VAPID_KEY \
    VITE_BASE=$VITE_BASE

RUN pnpm run build

# Stage 2: Production server
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3004

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

COPY server.js ./
COPY --from=builder /app/build ./build

EXPOSE 3004

CMD ["node", "server.js"]
